server {
    listen 80;
    
    # Where the static files are stored
    root /usr/share/nginx/html;
    
    # What file to serve as index
    index index.html index.htm;
    
    # Handle React routing: if file doesn't exist, fallback to index.html
    location / {
        try_files $uri $uri/ /index.html;
    }
}
